name: Bug report
description: Report a bug.
title: "[BUG] <Please write a descriptive title here>"

body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to file a bug report. Before you create a new issue please do the following:
      - Consider if the problem you have is a (suspected) bug. If not, you should open a discussion [here](https://github.com/theOehrly/Fast-F1/discussions) instead.
      - Ensure that you have updated to the latest version of FastF1.
      - Check the issue section to see if there is already an issue discussing your problem.

- type: textarea
  attributes:
    label: "Describe the issue:"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Reproduce the code example:"
    description: >
      A short code example that reproduces the problem.
      This should be a self contained script that can just be run as is.
    placeholder: |
      << your code here >>
    render: python
  validations:
    required: true

- type: textarea
  attributes:
    label: "Error message:"
    description: >
      Please include full error message including all logging output.
    placeholder: |
      << Full traceback starting from `Traceback: ...` >>
    render: shell
