name: Deploy Documentation from External Repo


on:
  workflow_dispatch:


jobs:
  fetch:
    name: Fetch Documentation Build from Exteral Repo
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Documentation build directory
        run: |
          mkdir -p docs/_build/html

      - name: Checkout documentation build from external repo
        uses: actions/checkout@v5
        # skip for pull requests (no access to secret + unversioned build is sufficient)
        with:
          repository: theOehrly/fastf1-doc-build-output
          path: docs/_build/html
          token: ${{ secrets.GH_PAT_DOC_BUILD_REPO }}
  
      - name: Upload docs as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html/


  deploy:
    name: Deploy Documentation

    # Add a dependency to the fetch job
    needs: fetch

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
